function(build_file_list)
    file(GLOB_RECURSE HPP_FILES "${CMAKE_CURRENT_SOURCE_DIR}/*.h*")
    file(GLOB_RECURSE SRC_CPP_FILES "${CMAKE_CURRENT_SOURCE_DIR}/*.*pp")
    file(GLOB_RECURSE SRC_C_FILES "${CMAKE_CURRENT_SOURCE_DIR}/*.c")
    set(ALL_FILES ${HPP_FILES} ${SRC_CPP_FILES} ${SRC_C_FILES} PARENT_SCOPE)
endfunction()

macro(build_application)
    build_file_list()
    message(STATUS "${PROJECT_NAME} is building as an executable")
    add_executable(${PROJECT_NAME} ${ALL_FILES})
endmacro()

macro(build_library)
    build_file_list()
    message(STATUS "${PROJECT_NAME} is building as a static library")
    add_library(${PROJECT_NAME} STATIC ${ALL_FILES})
    target_link_libraries(${PROJECT_NAME} PUBLIC ${COMMON_MODULES})
endmacro()
